# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJGP84x6qfLyVYJaF87zkjGdGKWut90J
"""

import streamlit as st

# Page setup
st.set_page_config(page_title="Affiliate Calculator", layout="centered")
st.title("Affiliate Revenue Calculator")

# Inputs
retailers = st.slider("Number Of Retailers", 1, 100, 1)
purchases = st.slider("Avg Number Of Purchases Per Month", 1, 50, 24)
sale_amount = st.number_input("Your Affiliate Sale (USD)", 0.0, 1_000_000.0, 49.00, 0.01)

# Calculation
monthly_profit = sale_amount * retailers * purchases

# Display
st.write("---")
st.markdown(
    f"<h1 style='color:#222;'>${monthly_profit:,.2f}</h1>",
    unsafe_allow_html=True
)