# -*- coding: utf-8 -*-
"""apps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6LJSgCUiOKTfNWFXP9r1seF-95SxrvL
"""

import streamlit as st

st.set_page_config(
    page_title="Affiliate Earnings Calculator",
    page_icon="💰",
    layout="centered",
    initial_sidebar_state="collapsed",
)

st.title("Affiliate Earnings Calculator")
st.write(
    """
    Adjust the sliders and input below to estimate your monthly profit.
    """
)

# 1. Number Of Retailers slider (1 to 200, default 100)
num_retailers = st.slider(
    label="Number Of Retailers",
    min_value=1,
    max_value=200,
    value=100,
    step=1,
)

# 2. Avg Number Of Purchases Per Mo. slider (1 to 200, default 50)
avg_purchases_per_month = st.slider(
    label="Avg Number Of Purchases Per Mo.",
    min_value=1,
    max_value=200,
    value=50,
    step=1,
)

# 3. Your Affiliate Sale numeric input (default 49.00)
affiliate_sale = st.number_input(
    label="Your Affiliate Sale",
    min_value=0.00,
    max_value=10000.00,
    value=49.00,
    step=1.00,
    format="%.2f",
)

# Calculate Monthly Profit
monthly_profit = num_retailers * avg_purchases_per_month * affiliate_sale

# Display result in a styled card
st.markdown("---")
st.markdown(
    f"""
    <div style="
        background-color: #111111;
        padding: 20px;
        border-radius: 8px;
        text-align: center;
    ">
        <span style="
            color: #ffffff;
            font-size: 48px;
            font-weight: bold;
        ">
            ${monthly_profit:,.0f}
        </span>
        <div style="color: #ffffff; font-size: 18px; margin-top: 5px;">
            Monthly Profit
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)