# -*- coding: utf-8 -*-
"""appss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6LJSgCUiOKTfNWFXP9r1seF-95SxrvL
"""

import streamlit as st

# --------------------------------------------
# 1) Page config: title, icon, layout
# --------------------------------------------
st.set_page_config(
    page_title="Affiliate Earnings Calculator",
    page_icon="💰",
    layout="centered",
    initial_sidebar_state="collapsed",
)

# --------------------------------------------
# 2) Force page background to pure white
#    (so the input area sits on a white card, as in the screenshot)
# --------------------------------------------
st.markdown(
    """
    <style>
        /* Make the entire app background white */
        .stApp {
            background-color: #FFFFFF;
        }
        /* Hide the default Streamlit top bar and footer (optional) */
        header, footer {
            visibility: hidden;
        }
        /* Ensure the main container also stays white */
        .css-18e3th9 {
            background-color: #FFFFFF;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

# --------------------------------------------
# 3) Title & description
# --------------------------------------------
st.title("Affiliate Earnings Calculator")
st.write(
    """
    Adjust the sliders and input below to estimate your monthly profit.
    """
)

# --------------------------------------------
# 4) Slider 1: Number Of Retailers (1 → 200, default 100)
# --------------------------------------------
num_retailers = st.slider(
    label="Number Of Retailers",
    min_value=1,
    max_value=200,
    value=100,
    step=1,
)

# --------------------------------------------
# 5) Slider 2: Avg Number Of Purchases Per Mo. (1 → 200, default 50)
# --------------------------------------------
avg_purchases_per_month = st.slider(
    label="Avg Number Of Purchases Per Mo.",
    min_value=1,
    max_value=200,
    value=50,
    step=1,
)

# --------------------------------------------
# 6) Numeric Input: Your Affiliate Sale ($49.00 default)
# --------------------------------------------
affiliate_sale = st.number_input(
    label="Your Affiliate Sale ($USD)",
    min_value=0.00,
    max_value=10000.00,
    value=49.00,
    step=1.00,
    format="%.2f",
)

# --------------------------------------------
# 7) Compute Monthly Profit
#    Formula: Number_Of_Retailers × Avg_Purchases_Per_Month × Affiliate_Sale
# --------------------------------------------
monthly_profit = num_retailers * avg_purchases_per_month * affiliate_sale

# --------------------------------------------
# 8) Display the result in a dark‐gray “card” identical to the screenshot
#    (Use #333333 background, white text, large bold number, small label)
# --------------------------------------------
st.markdown("---")
st.markdown(
    f"""
    <div style="
        background-color: #333333;
        padding: 20px;
        border-radius: 8px;
        text-align: center;
        margin-top: 10px;
    ">
        <span style="
            color: #ffffff;
            font-size: 48px;
            font-weight: bold;
        ">
            ${monthly_profit:,.0f}
        </span>
        <div style="
            color: #ffffff;
            font-size: 18px;
            margin-top: 5px;
        ">
            Monthly Profit
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)